web:
  image: syntithenai/cmfive
  ports:
    - "8090:80"
  volumes:
    - ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    - ./www:/var/www
  links:
    - php
php:
  image: nmcteam/php56
  ports:
    - "9000:9000"
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./www:/var/www
  links:
    - db
db:
  image: tutum/mysql
  ports:
    - "3306:3306"
  volumes:
   - /var/lib/mysql
   - ./db-dump/install.sql:/install.sql
  environment:
   - MYSQL_USER=admin
   - MYSQL_PASS=admin
   - ON_CREATE_DB=cmfive
   - STARTUP_SQL=/install.sql
