cmfivecomplete:
  image: 2pisoftware/cmfive
  ports:
    - "80"
    - "22"
    - "3306"
  volumes:
    - ${DOCKERMANAGER_WEB_ROOT}:/var/www
    - ../../src/cmfive/environment.cmfive.docker.csv:/environment.cmfive.docker.csv
#    - ../../database:/var/lib/mysql
    - ./src/nginx/keys/cacert.pem:/etc/nginx/certs/default.crt
    - ./src/nginx/keys/privkey.pem:/etc/nginx/certs/default.key
  links:
    - cmfivemysqlserver
  environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - CERT_NAME=default
  restart: always    
  
cmfivemysqlserver: 
  image: 2pisoftware/cmfive
  ports:
    - "3306"
#  volumes:
#    - /var/lib/mysql
  restart: always    

testrunner:
  image: 2pisoftware/cmfive
  volumes:
    - ${DOCKERMANAGER_WEB_ROOT}:/var/www
    - ../../src/cmfive/environment.testrunner.docker.csv:/environment.cmfive.docker.csv
  links:
    - selenium
    - cmfivecomplete
    - cmfivemysqlserver
  restart: always 
  
selenium:
  image: selenium/standalone-firefox-debug
  ports: 
    - "4444"
    - "5900"
  volumes:
    - "/dev/shm:/dev/shm"
  links:
    - cmfivecomplete
  restart: always 
