cmfivecomplete:
  image: 2pisoftware/cmfive
  ports:
    - "80"
    - "22"
    - "3306"
  volumes:
#    - ../../database:/var/lib/mysql
    - ../../web:/var/www
    - ../../src/cmfive/environment.cmfive.docker.csv:/environment.cmfive.docker.csv
  environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
  restart: always     

testrunner:
  image: 2pisoftware/cmfive
  volumes:
    - /var/www
    - ../../src/cmfive/environment.testrunner.docker.csv:/environment.cmfive.docker.csv
  links:
    - selenium
    - cmfivecomplete
  restart: always 
  
selenium:
  image: selenium/standalone-firefox-debug
  ports: 
    - "4444"
    - "5900"
  volumes:
    - "/dev/shm:/dev/shm"
  links:
    - cmfivecomplete
  restart: always 
