cmfivecomplete:
  image: 2pisoftware/cmfive
  ports:
    - "80"
    - "22"
    - "3306"
  volumes:
    - ./../../web:/var/www
  environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
  restart: always     

testrunner:
  image: 2pisoftware/cmfive
  volumes:
    - ./../../web:/var/www
  links:
    - selenium
    - cmfivecomplete
  restart: always 
  
selenium:
  image: selenium/standalone-firefox-debug
  ports: 
    - "4444"
    - "5900"
  volumes:
    - "/dev/shm:/dev/shm"
  links:
    - cmfivecomplete
  restart: always 
