cmfivecomplete:
  image: 2pisoftware/cmfive
  ports:
    - "80"
    - "22"
    - "3306"
  volumes:
    - /var/www
    - /var/lib/mysql
  environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}  
  restart: always     

testrunner:
  image: 2pisoftware/cmfive
  links:
    - selenium
    - cmfivecomplete

selenium:
  image: selenium/standalone-chrome-debug
  ports: 
    - "4444"
    - "5900"
  volumes:
    - "/dev/shm:/dev/shm"
  links:
    - cmfivecomplete

