web:
  image: syntithenai/cmfive
  ports:
    - "80"
  volumes:
    - .\www:/var/www/html
    - ./src/nginx.default:/etc/nginx/sites-enabled/default
  links:
    - php
  environment:
   - VIRTUAL_HOST=blah.d
php:
  image: nmcteam/php56
  ports:
    - "9000:9000"
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - .\www:/var/www/html
  links:
    - db
db:
  image: tutum/mysql
  ports:
    - "3306:3306"
  volumes:
   - /var/lib/mysql
   - ./db-dump/install.sql:/install.sql
  environment:
   - MYSQL_USER=admin
   - MYSQL_PASS=admin
   - ON_CREATE_DB=cmfive
   - STARTUP_SQL=/install.sql
